apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-store-config
  namespace: tech-store
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: techstore
  DB_URL: jdbc:postgresql://postgres:5432/techstore
  INVENTORY_URL: http://inventory-service:8081
