apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lab-app
type: Opaque
stringData:
  # En un entorno productivo real, esto debería gestionarse con AWS Secrets Manager,
  # External Secrets Operator o Sealed Secrets. Para el laboratorio usamos stringData.
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password123"
  POSTGRES_DB: "labdb"
