apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tech-store
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 03-postgres-statefulset.yaml
  - 04-postgres-service.yaml
  - 10-inventory-deployment.yaml
  - 11-inventory-service.yaml
  - 20-sales-deployment.yaml
  - 21-sales-service.yaml
  - 30-web-deployment.yaml
  - 31-web-service.yaml
  - 40-ingress.yaml
